# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loo_cpp_ <- function(log_lik, r_eff, auto_r_eff, save_psis) {
    .Call(`_posteriorcpp_loo_cpp_`, log_lik, r_eff, auto_r_eff, save_psis)
}

summarise_draws_cpp_ <- function(draws, stats) {
    .Call(`_posteriorcpp_summarise_draws_cpp_`, draws, stats)
}

